"""initial schema

Revision ID: 2adacd12a4a8
Revises: 
Create Date: 2026-09-06 21:42:57.355076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2adacd12a4a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=8), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievement_code'), ['code'], unique=True)

    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(trim(username)) > 0', name='ck_admin_username_not_blank'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_user_username'), ['username'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_log_actor', ['actor_type', 'actor_id'], unique=False)
        batch_op.create_index('ix_audit_log_created', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_log_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=8), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(name) <= 50', name='ck_child_name_length'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_child_name_not_blank'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_child_active'), ['active'], unique=False)

    op.create_table('reward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=8), nullable=False),
    sa.Column('points_required', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_reward_name_not_blank'),
    sa.CheckConstraint('points_required >= 1 AND points_required <= 10000', name='ck_reward_points_range'),
    sa.CheckConstraint('quantity IS NULL OR quantity >= 0', name='ck_reward_quantity'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reward_active'), ['active'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('repeat_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name='ck_task_date_range'),
    sa.CheckConstraint('length(trim(title)) > 0', name='ck_task_title_not_blank'),
    sa.CheckConstraint('points >= 1 AND points <= 100', name='ck_task_points_range'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_active'), ['active'], unique=False)
        batch_op.create_index('ix_task_active_category', ['active', 'category'], unique=False)

    op.create_table('child_achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'achievement_id', name='uq_child_achievement')
    )
    with op.batch_alter_table('child_achievement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_child_achievement_child_id'), ['child_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('ix_notification_child_unread', ['child_id', 'read_at'], unique=False)

    op.create_table('point_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("transaction_type IN ('EARN','DEDUCT','REDEEM','ADJUST','BONUS')", name='ck_point_transaction_type'),
    sa.CheckConstraint('points <> 0', name='ck_point_transaction_points_nonzero'),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['admin_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', 'transaction_type', name='uq_point_transaction_source')
    )
    with op.batch_alter_table('point_transaction', schema=None) as batch_op:
        batch_op.create_index('ix_point_transaction_child_created', ['child_id', 'created_at'], unique=False)
        batch_op.create_index('ix_point_transaction_child_type', ['child_id', 'transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_point_transaction_created_at'), ['created_at'], unique=False)

    op.create_table('reward_redemption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=False),
    sa.Column('reward_name_snapshot', sa.String(length=100), nullable=False),
    sa.Column('reward_icon_snapshot', sa.String(length=8), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('REQUESTED','APPROVED','COMPLETED','CANCELLED','REJECTED')", name='ck_redemption_status'),
    sa.CheckConstraint('points >= 0', name='ck_redemption_points'),
    sa.ForeignKeyConstraint(['approved_by'], ['admin_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reward_id'], ['reward.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reward_redemption', schema=None) as batch_op:
        batch_op.create_index('ix_redemption_child_requested', ['child_id', 'requested_at'], unique=False)
        batch_op.create_index('ix_redemption_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reward_redemption_reward_id'), ['reward_id'], unique=False)

    op.create_table('task_assignee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'child_id', name='uq_task_assignee')
    )
    with op.batch_alter_table('task_assignee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_assignee_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_assignee_task_id'), ['task_id'], unique=False)

    op.create_table('task_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('assignment_date', sa.Date(), nullable=False),
    sa.Column('task_title_snapshot', sa.String(length=100), nullable=False),
    sa.Column('task_icon_snapshot', sa.String(length=8), nullable=False),
    sa.Column('points_snapshot', sa.Integer(), nullable=False),
    sa.Column('required_snapshot', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('earned_points', sa.Integer(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('TODO','WAITING_APPROVAL','APPROVED','REJECTED')", name='ck_assignment_status'),
    sa.CheckConstraint('earned_points >= 0', name='ck_assignment_earned_points'),
    sa.CheckConstraint('points_snapshot >= 0', name='ck_assignment_points_snapshot'),
    sa.ForeignKeyConstraint(['approved_by'], ['admin_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'child_id', 'assignment_date', name='uq_assignment_task_child_date')
    )
    with op.batch_alter_table('task_assignment', schema=None) as batch_op:
        batch_op.create_index('ix_assignment_child_date', ['child_id', 'assignment_date'], unique=False)
        batch_op.create_index('ix_assignment_status', ['status'], unique=False)
        batch_op.create_index('ix_assignment_status_date', ['status', 'assignment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_assignment_task_id'), ['task_id'], unique=False)

    op.create_table('task_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.String(length=3), nullable=False),
    sa.CheckConstraint("weekday IN ('MON','TUE','WED','THU','FRI','SAT','SUN')", name='ck_task_schedule_weekday'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'weekday', name='uq_task_schedule_task_weekday')
    )
    with op.batch_alter_table('task_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_schedule_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_schedule_task_id'))

    op.drop_table('task_schedule')
    with op.batch_alter_table('task_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_assignment_task_id'))
        batch_op.drop_index('ix_assignment_status_date')
        batch_op.drop_index('ix_assignment_status')
        batch_op.drop_index('ix_assignment_child_date')

    op.drop_table('task_assignment')
    with op.batch_alter_table('task_assignee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_assignee_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_assignee_child_id'))

    op.drop_table('task_assignee')
    with op.batch_alter_table('reward_redemption', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reward_redemption_reward_id'))
        batch_op.drop_index('ix_redemption_status')
        batch_op.drop_index('ix_redemption_child_requested')

    op.drop_table('reward_redemption')
    with op.batch_alter_table('point_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_point_transaction_created_at'))
        batch_op.drop_index('ix_point_transaction_child_type')
        batch_op.drop_index('ix_point_transaction_child_created')

    op.drop_table('point_transaction')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_child_unread')

    op.drop_table('notification')
    with op.batch_alter_table('child_achievement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_child_achievement_child_id'))

    op.drop_table('child_achievement')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index('ix_task_active_category')
        batch_op.drop_index(batch_op.f('ix_task_active'))

    op.drop_table('task')
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reward_active'))

    op.drop_table('reward')
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_child_active'))

    op.drop_table('child')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_entity')
        batch_op.drop_index('ix_audit_log_created')
        batch_op.drop_index('ix_audit_log_actor')
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_user_username'))

    op.drop_table('admin_user')
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievement_code'))

    op.drop_table('achievement')
    # ### end Alembic commands ###
