"""add app_setting table

Revision ID: eae29d23e520
Revises: 2adacd12a4a8
Create Date: 2026-09-07 22:29:48.641687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae29d23e520'
down_revision = '2adacd12a4a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(trim(key)) > 0', name='ck_app_setting_key_not_blank'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_setting_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_setting_key'))

    op.drop_table('app_setting')
    # ### end Alembic commands ###
